name: tic_tac_toe
description: A small app for demonstrating Dart language features.
version: 1.0.0
homepage: https://github.com/Brady-Simon/language-demo

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
